<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ManishkumarG-MS" ignored="3" name="Default test(failed)(failed)" tests="1" failures="1" timestamp="16 Aug 2019 12:30:23 GMT" time="11.398" errors="0">
  <testcase name="TestExample3" time="0.002" classname="test.AlertBoxTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.AlertBoxTest.TestExample3(AlertBoxTest.java:58)
at Runner.TestRunner.main(TestRunner.java:16)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TestExample3 -->
  <testcase name="testExample2" time="0.0" classname="test.AlertBoxTest">
    <ignored/>
  </testcase> <!-- testExample2 -->
  <testcase name="testPositionData" time="0.0" classname="test.AlertBoxTest">
    <ignored/>
  </testcase> <!-- testPositionData -->
  <testcase name="testexample" time="0.0" classname="test.AlertBoxTest">
    <ignored/>
  </testcase> <!-- testexample -->
</testsuite> <!-- Default test(failed)(failed) -->
